
name: DEPLOY
run-name: DEPLOY

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - 'feature'

jobs:
  # Build job
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: .

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]

    steps:
        # To use this repository's private action, you must check out the repository
        - name: 🛒 CHECKOUT
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GIT_TOKEN }}

        - name: Preset Image Name
          run: echo "IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

        - name: Build and push Docker Image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ env.IMAGE_URL }}

        - name: Deploy Image to CapRrover
          uses: caprover/deploy-from-github@v1.1.2
          with:
            server: "${{ secrets.CAPROVER_SERVER }}"
            app: "${{ secrets.APP_NAME }}"
            token: "${{ secrets.APP_TOKEN }}"
            image: ${{ env.IMAGE_URL }}
