
name: studio-nuxt-build
run-name: studio nuxt build

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Add write workflow permissions
permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: .

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]

    steps:
       # To use this repository's private action, you must check out the repository
        - name: 🛒 CHECKOUT
          uses: actions/checkout@v2
        
        - uses: actions/setup-node@v4
          with:
            node-version: 22.3.0
            

        - name: 🛠️ BUILD OUR APP
          run: | 
            export NODE_OPTIONS="--max-old-space-size=4096"
            yarn install
            yarn run build

        - name: PACK BUILD FILE
          uses: a7ul/tar-action@v1.1.0
          with:
            command: c
            cwd: "./"
            files: |
              ./.output/public/
              captain-definition
            outPath: deploy.tar

        - name: 🗿 DEPLOY BUILD TO SERVER
          uses: caprover/deploy-from-github@v1.0.1
          with:
            server: '${{ secrets.CAPROVER_SERVER }}'
            app: '${{ secrets.APP_NAME }}'
            token: '${{ secrets.APP_TOKEN }}'
