
name: studio-nuxt-build
run-name: studio nuxt build

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - 'main'

jobs:
  # Build job
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: .

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]

    steps:
        # To use this repository's private action, you must check out the repository
        - name: 🛒 CHECKOUT
          uses: actions/checkout@v4

        - name: PACK BUILD FILE
          uses: a7ul/tar-action@v1.1.0
          with:
            command: c
            cwd: "./"
            files: |
              ./
            outPath: deploy.tar

        - name: 🗿 DEPLOY FILE TO SERVER
          uses: caprover/deploy-from-github@v1.0.1
          with:
            server: '${{ secrets.CAPROVER_SERVER }}'
            app: '${{ secrets.APP_NAME }}'
            token: '${{ secrets.APP_TOKEN }}'
